stages:
  generar_datos:
    cmd: python src/get_data.py
    deps:
      - src/get_data.py
    outs:
      - data/train_features.csv
      - data/test_features.csv
      - data/train_labels.csv
      - data/test_labels.csv
  entrenar_modelo:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/train_features.csv
      - data/train_labels.csv
    params:
      - seed
    outs:
      - model.pkl
    metrics:
      - metrics.json
    plots:
      - loss.csv
